language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: nJIfeAyVeNIDXAH68une9fflBreZyv823O8pPmqoahdfbfSJoHNiHQHBiFNzF5f7nBaW+zis/7hbpHJRTR8ijhb+IqMXdCCEnB0qpToIxYmpCJ3cuPUNvJhFxGw7Mu9O8nntX8LQr7r1TTifeslyfzH5FVHIW3XDRtafu/3Gy4ZTdbptZ+OVX5GqzIij9nXeknb8V8nek/18G6PCEnETm4JzZsKjDhztiPruIG7+faHNCeIRZ5x0w7385s/RwHBUBuxrmI5xjsTF3b0VWWJnJspsZrtEnNEdn6laFfiibDrM9KyfBl/dNetViL8wWXhfaYDTBOkfnZOcTUxTJStSP08jvbPbcJZPcH2FvuA/dC6QIqZlfvnt+/X1yOqUFPju+PLKlH0izGTiU1pgTr94lBJkspTVyltn/Dfkt6FRyfNqK1rKxYzC3PNzcEZqoLIkkHSZif4RT9Yn0U+/TXI/U67vsUnBWogTqRzMqPDGrnEHc0qxCGuj0dOd+9nheZmuJiEI8gSLI3qNKXRyJqiIe84EdK9P4ynIpnxEBqmyTCAe5znnQ8ZEJiDfvBRxEXdGeHDYA3ERcRVhmeOLYYAVO2KXQQGUd9hVQvtIQCnmDPCFtbILj3co6ATyg4wD7uSYtmPLPrDFwkhJYT1aNOB8yftoKaHG/pDqHeU0pm+5efs=
